// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbeSeqKML-2jGc34M-ONJm0JtpJw96OoU',
    appId: '1:1042039723796:web:372e72c02ab3d114a29401',
    messagingSenderId: '1042039723796',
    projectId: 'oraculo-89b67',
    authDomain: 'oraculo-89b67.firebaseapp.com',
    storageBucket: 'oraculo-89b67.firebasestorage.app',
    measurementId: 'G-BDMH62TJQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCA2KlLtwPpGqc5gJoHK6bUxKlkLPgss',
    appId: '1:1042039723796:android:9eb42d239ec4b1a7a29401',
    messagingSenderId: '1042039723796',
    projectId: 'oraculo-89b67',
    storageBucket: 'oraculo-89b67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzt20eihuQF0ttm83mif7A_rIEHQABWUA',
    appId: '1:1042039723796:ios:ce410b62e29d838aa29401',
    messagingSenderId: '1042039723796',
    projectId: 'oraculo-89b67',
    storageBucket: 'oraculo-89b67.firebasestorage.app',
    iosBundleId: 'com.example.oraculo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzt20eihuQF0ttm83mif7A_rIEHQABWUA',
    appId: '1:1042039723796:ios:ce410b62e29d838aa29401',
    messagingSenderId: '1042039723796',
    projectId: 'oraculo-89b67',
    storageBucket: 'oraculo-89b67.firebasestorage.app',
    iosBundleId: 'com.example.oraculo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbeSeqKML-2jGc34M-ONJm0JtpJw96OoU',
    appId: '1:1042039723796:web:cfbbe0d6968721fea29401',
    messagingSenderId: '1042039723796',
    projectId: 'oraculo-89b67',
    authDomain: 'oraculo-89b67.firebaseapp.com',
    storageBucket: 'oraculo-89b67.firebasestorage.app',
    measurementId: 'G-SZ0WNZK3FW',
  );
}
